### model
model_name_or_path: Qwen/Qwen3-4B
adapter_name_or_path: saves/qwen3-4b/lora/finance_sft_json
trust_remote_code: true

### method
finetuning_type: lora

### dataset
template: qwen3_nothink

### generation
max_new_tokens: 768
temperature: 0.2
top_p: 0.8
repetition_penalty: 1.1
